book/urls.py
from django.urls import path
from book import views

urlpatterns = [
    path('create-new-book/', views.BookCreateView.as_view(), name='create_new_book'),
    path('list-of-books/', views.BookListView.as_view(), name='all_books'),
    path('update-book/<int:pk>/', views.BookUpdateView.as_view(), name='update_book')
]

djangoProjectSDA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('intro.urls')),
    path('', include('student.urls')),
    path('', include('teacher.urls')),
    path('', include('home.urls')),
    path('', include('book.urls')),
    path('', include('userextend.urls')),
    path('', include('django.contrib.auth.urls')),
]

student/urls.py
from django.urls import path
from student import views

urlpatterns = [
    path('create-new-student/', views.StudentCreateView.as_view(), name='create_new_student'),
    path('list-of-students/', views.StudentListView.as_view(), name='all_students'),
    path('update-student/<int:pk>/', views.StudentUpdateView.as_view(), name='update_student'),
    path('student-details/<int:pk>/', views.StudentDetailView.as_view(), name='details_student'),
    path('delete-student/<int:pk>/', views.StudentDeleteView.as_view(), name='delete_student'),
    path('inactive-student/<int:pk>/', views.inactive_student, name='inactive_student')
]

student/models.py
from django.db import models

from teacher.models import Teacher


class Student(models.Model):
    gender_options = (('male', 'Male'), ('female', 'Female'), ('other', 'Other'))

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(max_length=100)
    age = models.IntegerField()
    description = models.TextField()
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    is_olympic = models.BooleanField(default=False)
    gender = models.CharField(max_length=6, choices=gender_options)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, null=True)

    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

student/forms.py
from django import forms
from django.forms import TextInput, EmailInput, Textarea, DateTimeInput, Select

from student.models import Student


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'age', 'email', 'description','start_date', 'end_date',
                  'is_olympic', 'gender', 'teacher']
        widgets = {
            'first_name': TextInput(attrs={'placeholder': 'Please enter your first name', 'class': 'form-control'}),
            'last_name': TextInput(attrs={'placeholder': 'Please enter your last name', 'class': 'form-control'}),
            'age': TextInput(attrs={'placeholder': 'Please enter your age', 'class': 'form-control'}),
            'email': EmailInput(attrs={'placeholder': 'Please enter your email', 'class': 'form-control'}),
            'description': Textarea(attrs={'placeholder': 'Please enter your description', 'class': 'form-control'}),
            'start_date': DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'end_date': DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'gender': Select(attrs={'class': 'form-select'}),
            'teacher': Select(attrs={'class': 'form-select'})
        }

student/views.py
# from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView

from student.forms import StudentForm
from student.models import Student


class StudentCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    template_name = 'student/create_student.html'  #calea catre fisierul html
    model = Student
    form_class = StudentForm
    success_url = reverse_lazy('create_new_student')
    permission_required = 'student.add_student'


class StudentListView(LoginRequiredMixin, ListView):
    template_name = 'student/list_of_students.html'
    model = Student
    context_object_name = 'all_students'

    def get_queryset(self):
        return Student.objects.filter(active=True)


class StudentUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = 'student/update_student.html'
    model = Student
    form_class = StudentForm
    success_url = reverse_lazy('all_students')


class StudentDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    template_name = 'student/details_student.html'
    model = Student


class StudentDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    template_name = 'student/delete_student.html'
    model = Student
    success_url = reverse_lazy('all_students')


@login_required
@permission_required('inactivate_student')
def inactive_student(request, pk):
    Student.objects.filter(id=pk).update(active=False)
    return redirect('all_students')

templates/student/create_student.html
{% extends 'base.html' %}
{% block title %} Create a new student {% endblock %}
{% block content %}
    <div class="container"><br><br>
        <div class="row">
              <div class="col-md-6 offset-md-3">
                  <div class="card">
                      <div class="card-header">
                          <h3 class="text-center">Create a new student</h3>
                      </div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form.as_p }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </form>
                  </div>
              </div>
        </div>
    </div>

{% endblock %}

templates/student/delete_student.html
{% extends 'base.html' %}
{% block title %} Delete - {{ student.first_name }} {{ student.last_name }} {% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <h3 class="text-center"> Are you sure you want to delete {{ student.first_name }} {{ student.last_name }}</h3>
                </div>
                <div class="card-footer text-center">
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success btn-sm">Yes</button>
                        <a href="{% url 'all_students' %}" class="btn btn-secondary btn-sm">No</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/student/details_student.html
{% extends 'base.html' %}
{% block title %} Student details {% endblock %}
{% block content %}<br>
    <div class="card mx-auto" style="width: 18rem;">
        <div class="card-header">
            <h4>{{ student.first_name }} {{ student.last_name }}</h4>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Email: {{ student.email }}</li>
            <li class="list-group-item">Age: {{ student.age }}</li>
            <li class="list-group-item">Description: {{ student.description }}</li>
            <li class="list-group-item">Is olympic: {{ student.is_olympic }}</li>
            <li class="list-group-item">Gender: {{ student.gender }}</li>
            <li class="list-group-item">Teacher: {{ student.teacher.first_name }} {{ student.teacher.last_name }}</li>
            <li class="list-group-item">Start date: {{ student.start_date }}</li>
            <li class="list-group-item">End date: {{ student.end_date }}</li>
        </ul>
    </div>
{% endblock %}

templates/student/list_of_students.html
{% extends 'base.html' %}

{% block title %} List of students {% endblock %}
{% block content %}
    <div class="container"><br><br>
        <div class="row">
            <div class="col-md-12 offset-md-0">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">First name</th>
                            <th scope="col">Last name</th>
                            <th scope="col">Is olympic?</th>
                            <th scope="col">Start date</th>
                            <th scope="col">End date</th>
                            <th scope="col">Description</th>
                            <th scope="col">Age</th>
                            <th scope="col">Teacher</th>
                            <th scope="col">Department</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody class="table-group-divider">
                        {% for student in all_students %}
                            <tr>
                                <td>{{ student.first_name }}</td>
                                <td>{{ student.last_name }}</td>
                                <td>{{ student.is_olympic }}</td>
                                <td>{{ student.start_date }}</td>
                                <td>{{ student.end_date }}</td>
                                <td>{{ student.description }}</td>
                                <td>{{ student.age }}</td>
                                <td>{{ student.teacher }}</td>
                                <td>{{ student.teacher.department }}</td>
                                <td>
                                    <div class="dropdown">
                                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                            Actions
                                        </button>
                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                            {% if perms.student.change_student %}
                                                <li><a class="dropdown-item" href="#">
                                                    <a href="{% url 'update_student' student.id %}" class="dropdown-item">Update</a>
                                                </a></li>
                                            {% endif %}
                                            {% if perms.student.details_student %}
                                                <li><a class="dropdown-item" href="#">
                                                    <a href="{% url 'details_student' student.id %}" class="dropdown-item">Details</a>
                                                </a></li>
                                            {% endif %}
                                            {% if perms.student.inactivate_student %}
                                                <li><a class="dropdown-item" href="#">
                                                    <a href="{% url 'inactive_student' student.id %}" class="dropdown-item">Make inactive</a>
                                                </a></li>
                                            {% endif %}
                                            {% if perms.student.delete_student %}
                                                <li><a class="dropdown-item" href="#">
                                                    <a href="{% url 'delete_student' student.id %}" class="dropdown-item">Delete</a>
                                                </a></li>
                                            {% endif %}
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/student/update_student.html
{% extends 'base.html' %}
{% block title %} Update student {% endblock %}
{% block content %}
    <div class="container"><br><br>
        <div class="row">
              <div class="col-md-6 offset-md-3">
                  <div class="card">
                      <div class="card-header">
                          <h3 class="text-center">Update student</h3>
                      </div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form.as_p }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </form>
                  </div>
              </div>
        </div>
    </div>

{% endblock %}