book/urls.py
from django.urls import path
from book import views

urlpatterns = [
    path('create-new-book/', views.BookCreateView.as_view(), name='create_new_book'),
    path('list-of-books/', views.BookListView.as_view(), name='all_books'),
    path('update-book/<int:pk>/', views.BookUpdateView.as_view(), name='update_book')
]

djangoProjectSDA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('intro.urls')),
    path('', include('student.urls')),
    path('', include('teacher.urls')),
    path('', include('home.urls')),
    path('', include('book.urls')),
    path('', include('userextend.urls')),
    path('', include('django.contrib.auth.urls')),
]

teacher/urls.py
from django.urls import path
from teacher import views

urlpatterns = [
    path('create-new-teacher/', views.TeacherCreateView.as_view(), name='create_new_teacher'),
    path('list-of-teachers/', views.TeacherListView.as_view(), name='all_teachers'),
    path('update-teacher/<int:pk>/', views.TeacherUpdateView.as_view(), name='update_teacher'),
    path('teacher-details/<int:pk>/', views.TeacherDetailView.as_view(), name='details_teacher'),
    path('delete-teacher/<int:pk>/', views.TeacherDeleteView.as_view(), name='delete_teacher'),
    path('inactive-teacher/<int:pk>/', views.inactive_teacher, name='inactive_teacher'),
    path('students-per-teacher/<int:pk>/', views.get_all_students_per_teacher, name='all_students_per_teacher')
    ]

teacher/models.py
from django.db import models

# Create your models here.


class Teacher(models.Model):
    department_options = (('python', 'Python'), ('java', 'Java'), ('c#', 'C#'))

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    department = models.CharField(max_length=6, choices=department_options)
    course = models.CharField(max_length=100)
    description = models.TextField()
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

teacher/forms.py
from django import forms
from django.forms import TextInput, EmailInput, Textarea, DateTimeInput, Select

from teacher.models import Teacher


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['first_name', 'last_name', 'department', 'course', 'description',
                  'start_date', 'end_date']
        widgets = {
            'first_name': TextInput(attrs={'placeholder': 'Please enter your first name', 'class': 'form-control'}),
            'last_name': TextInput(attrs={'placeholder': 'Please enter your last name', 'class': 'form-control'}),
            'department': Select(attrs={ 'class': 'form-control'}),
            'course': TextInput(attrs={'placeholder': 'Please enter your course', 'class': 'form-control'}),
            'description': Textarea(attrs={'placeholder': 'Please enter your description', 'class': 'form-control'}),
            'start_date': DateTimeInput(attrs={'class' : 'form-control', 'type': 'datetime-local'}),
            'end_date': DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
        }

teacher/views.py
# from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView

from student.models import Student
from teacher.forms import TeacherForm
from teacher.models import Teacher


class TeacherCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    template_name = 'teacher/create_teacher.html'
    model = Teacher
    # fields = '__all__'
    form_class = TeacherForm
    success_url = reverse_lazy('create_new_teacher')


class TeacherListView(LoginRequiredMixin, ListView):
    template_name = 'teacher/list_of_teachers.html'
    model = Teacher
    context_object_name = 'all_teachers'


class TeacherUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = 'teacher/update_teacher.html'
    model = Teacher
    form_class = TeacherForm
    success_url = reverse_lazy('all_teachers')


class TeacherDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    template_name = 'teacher/details_teacher.html'
    model = Teacher


class TeacherDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    template_name = 'teacher/delete_teacher.html'
    model = Teacher
    success_url = reverse_lazy('all_teachers')


@login_required
@permission_required('inactivate_teacher')
def inactive_teacher(request, pk):
    Teacher.objects.filter(id=pk).update(active=False)
    return redirect('all_teachers')


def get_all_students_per_teacher(request, pk):  # PK INSEMNAND id.ul profesorului
    all_students_per_teacher = Student.objects.filter(teacher_id=pk)
    context = {'all_students_per_teachers': all_students_per_teacher}
    return render(request, 'teacher/all_students_per_teacher.html', context)

templates/teacher/all_students_per_teacher.html
{% extends 'base.html' %}
{% block title %} List of students {% endblock %}
{% block content %}
    <div class="container"><br><br><br><br>
        <div class="row">
            <div class="col-md-8 offset-md-2">
            {% if all_students_per_teachers  %}
                <table class="table table-light table-striped table-bordered border-dark">

                    <thead>
                    <tr>
                        <th>First Name</th>
                        <th> Last Name</th>
                        <th> Is Oplympic?</th>
                        <th> Start Date</th>
                        <th> End Date</th>
                        <th> Description</th>
                        <th> Age</th>
                        <th> Teacher</th>
                        <th> Course</th>
                        <th> Actions</th>
                    </thead>
                    <tbody>
                    {% for student in all_students_per_teachers %}
                        <tr>
                            <td> {{ student.first_name }}</td>
                            <td> {{ student.last_name }}</td>
                            <td> {% if student.is_olympic is True %}  Yes {% else %} No {% endif %} </td>
                            <td> {{ student.start_date|date:"d-m-Y H:i:s" }}</td>
                            <td> {{ student.end_date|date:"d-m-Y H:i:s" }}</td>
                            <td> {{ student.description }}</td>
                            <td> {{ student.age }}</td>
                            <td>
                                {% if student.teacher %}
                                    {{ student.teacher }}
                                {% else %}
                                    No teacher
                                {% endif %}
                            </td>

                            <td>{% if student.teacher.course %}
                                {{ student.teacher.course }}
                            {% else %}
                                No course
                            {% endif %}
                            </td>


                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-danger dropdown-toggle"
                                            data-bs-toggle="dropdown" aria-expanded="false">
                                        Actions
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" href="{% url 'update_student'  student.id %}">Update</a>
                                        </li>
                                        <li><a class="dropdown-item" href="{% url 'details_student'  student.id %}">Details</a>
                                        </li>
                                        <li><a class="dropdown-item" href="{% url 'inactive_student'  student.id %}">Inactive</a>
                                        </li>
                                        <li>
                                            <hr class="dropdown-divider">
                                        </li>
                                        <li><a class="dropdown-item"
                                               href="{% url 'delete_student' student.id %}">Delete</a></li>

                                    </ul>
                                </div>
                            </td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h3 class="text-center">No data available</h3>

            {% endif %}
            </div>


        </div>
    </div>

{% endblock %}

templates/teacher/create_teacher.html
{% extends 'base.html' %}
{% block title %} Create a new teacher {% endblock %}
{% block content %}
    <div class="container"><br><br>
        <div class="row">
              <div class="col-md-6 offset-md-3">
                  <div class="card">
                      <div class="card-header">
                          <h3 class="text-center">Create a new teacher</h3>
                      </div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form.as_p }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </form>
                  </div>
              </div>
        </div>
    </div>

{% endblock %}

templates/teacher/delete_teacher.html
{% extends 'base.html' %}
{% block title %} Delete - {{ teacher.first_name }} {{ teacher.last_name }} {% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <h3 class="text-center"> Are you sure you want to delete {{ teacher.first_name }} {{ teacher.last_name }}</h3>
                </div>
                <div class="card-footer text-center">
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success btn-sm">Yes</button>
                        <a href="{% url 'all_teachers' %}" class="btn btn-secondary btn-sm">No</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/teacher/details_teacher.html
{% extends 'base.html' %}
{% block title %} Teacher details {% endblock %}
{% block content %}<br>
    <div class="card mx-auto" style="width: 18rem;">
        <div class="card-header">
            <h4>{{ teacher.first_name }} {{ teacher.last_name }}</h4>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Department: {{ teacher.department }}</li>
            <li class="list-group-item">Course: {{ teacher.course }}</li>
            <li class="list-group-item">Description: {{ teacher.description }}</li>

            <li class="list-group-item">Students: {% for student in all_students %}{% if student.teacher %}{{ student }}{% endif %}{% endfor %} {{ student.teacher.first_name }} {{ student.teacher.last_name }}</li>
            <li class="list-group-item">Start date: {{ teacher.start_date }}</li>
            <li class="list-group-item">End date: {{ teacher.end_date }}</li>
        </ul>
    </div>
{% endblock %}

templates/teacher/list_of_teachers.html
{#{% extends 'base.html' %}#}
{##}
{#{% block title %} List of teachers {% endblock %}#}
{#{% block content %}#}
{#    <div class="row">#}
{#        {% for teacher in all_teachers %}#}
{#            <div class="col-sm-4"><br>#}
{#                <div class="card" style="width: 25rem;">#}
{#                    <div class="card-header">{{ teacher.department }}</div>#}
{#                        <div class="card-body">#}
{#                            <h5 class="card-title">{{ teacher.first_name }} {{ teacher.last_name }}</h5>#}
{#                            <h6 class="card-title">Course: {{ teacher.course }}</h6>#}
{#                            <p class="card-text">{{ teacher.description }}</p>#}
{#                            <p class="card-text">{{ teacher.start_date}} - {{ teacher.end_date}}</p>#}
{#                        </div>#}
{#                    <div class="card-footer text-muted">#}
{#                        <a href="{% url 'update_teacher' teacher.id %}" class="btn btn-dark btn-sm">Update</a>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        {% endfor %}#}
{#    </div>#}
{#{% endblock %}#}

{% extends 'base.html' %}

{% block title %} List of teachers {% endblock %}
{% block content %}
    <div class="row">
        {% for teacher in all_teachers %}
            {% if teacher.active %}
            {% if teacher.department == 'c#' %}
                <div class="col-sm-4"><br>
                    <div class="card" style="max-width: 25rem;">
                        <div class="card-header text-bg-success mb-3">{{ teacher.department }}</div>
                            <div class="card-body">
                                <h5 class="card-title">{{ teacher.first_name }} {{ teacher.last_name }}</h5>
                                <h6 class="card-title">Course: {{ teacher.course }}</h6>
                                <p class="card-text">{{ teacher.description }}</p>
                                <p class="card-text">{{ teacher.start_date}} - {{ teacher.end_date}}</p>
                            </div>
                        <div class="card text-center">
{#                        <div class="card-footer text-muted">#}
{#                            <a href="{% url 'update_teacher' teacher.id %}" class="btn btn-success">Update</a>#}
{#                        </div>#}
                        <div class="dropdown">
                            <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                Actions
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                {% if perms.teacher.change_teacher %}
                                    <li><a class="dropdown-item" href="#">
                                        <a href="{% url 'update_teacher' teacher.id %}" class="dropdown-item">Update</a>
                                    </a></li>
                                {% endif %}
                                {% if perms.teacher.details_teacher %}
                                    <li><a class="dropdown-item" href="#">
                                        <a href="{% url 'details_teacher' teacher.id %}" class="dropdown-item">Details</a>
                                    </a></li>
                                {% endif %}
                                {% if perms.teacher.inactivate_teacher %}
                                    <li><a class="dropdown-item" href="#">
                                        <a href="{% url 'inactive_teacher' teacher.id %}" class="dropdown-item">Make inactive</a>
                                    </a></li>
                                {% endif %}
                                {% if perms.teacher.delete_teacher %}
                                    <li><a class="dropdown-item" href="#">
                                        <a href="{% url 'delete_teacher' teacher.id %}" class="dropdown-item">Delete</a>
                                    </a></li>
                                {% endif %}
                            </ul>
                        </div>
                        </div>
                    </div>
                </div>
{#            {% endif %}#}
            {% elif teacher.department == 'python' %}
                <div class="col-sm-4"><br>
                    <div class="card" style="max-width: 25rem;">
                        <div class="card-header text-bg-primary mb-3">{{ teacher.department }}</div>
                            <div class="card-body">
                                <h5 class="card-title">{{ teacher.first_name }} {{ teacher.last_name }}</h5>
                                <h6 class="card-title">Course: {{ teacher.course }}</h6>
                                <p class="card-text">{{ teacher.description }}</p>
                                <p class="card-text">{{ teacher.start_date}} - {{ teacher.end_date}}</p>
                            </div>
                        <div class="card text-center">
                        <div class="dropdown">
                            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                Actions
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                {% if perms.teacher.change_teacher %}
                                    <li><a class="dropdown-item" href="#">
                                        <a href="{% url 'update_teacher' teacher.id %}" class="dropdown-item">Update</a>
                                    </a></li>
                                {% endif %}
                                {% if perms.teacher.details_teacher %}
                                    <li><a class="dropdown-item" href="#">
                                        <a href="{% url 'details_teacher' teacher.id %}" class="dropdown-item">Details</a>
                                    </a></li>
                                {% endif %}
                                {% if perms.teacher.inactivate_teacher %}
                                    <li><a class="dropdown-item" href="#">
                                        <a href="{% url 'inactive_teacher' teacher.id %}" class="dropdown-item">Make inactive</a>
                                    </a></li>
                                {% endif %}
                                {% if perms.teacher.delete_teacher %}
                                    <li><a class="dropdown-item" href="#">
                                        <a href="{% url 'delete_teacher' teacher.id %}" class="dropdown-item">Delete</a>
                                    </a></li>
                                {% endif %}
                            </ul>
                        </div>
{#                        <div class="card-footer text-muted">#}
{#                            <a href="{% url 'update_teacher' teacher.id %}" class="btn btn-primary">Update</a>#}
{#                        </div>#}
                        </div>
                    </div>
                </div>
                {% elif teacher.department == 'java' %}
                <div class="col-sm-4"><br>
                    <div class="card" style="max-width: 25rem;">
                        <div class="card-header text-bg-warning mb-3">{{ teacher.department }}</div>
                            <div class="card-body">
                                <h5 class="card-title">{{ teacher.first_name }} {{ teacher.last_name }}</h5>
                                <h6 class="card-title">Course: {{ teacher.course }}</h6>
                                <p class="card-text">{{ teacher.description }}</p>
                                <p class="card-text">{{ teacher.start_date}} - {{ teacher.end_date}}</p>
                            </div>
                        <div class="card text-center">
                        <div class="dropdown">
                            <button class="btn btn-warning dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                Actions
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                {% if perms.teacher.change_teacher %}
                                    <li><a class="dropdown-item" href="#">
                                        <a href="{% url 'update_teacher' teacher.id %}" class="dropdown-item">Update</a>
                                    </a></li>
                                {% endif %}
                                {% if perms.teacher.details_teacher %}
                                    <li><a class="dropdown-item" href="#">
                                        <a href="{% url 'details_teacher' teacher.id %}" class="dropdown-item">Details</a>
                                    </a></li>
                                {% endif %}
                                {% if perms.teacher.inactivate_teacher %}
                                    <li><a class="dropdown-item" href="#">
                                        <a href="{% url 'inactive_teacher' teacher.id %}" class="dropdown-item">Make inactive</a>
                                    </a></li>
                                {% endif %}
                                {% if perms.teacher.delete_teacher %}
                                    <li><a class="dropdown-item" href="#">
                                        <a href="{% url 'delete_teacher' teacher.id %}" class="dropdown-item">Delete</a>
                                    </a></li>
                                {% endif %}
                            </ul>
                        </div>
{#                        <div class="card-footer text-muted">#}
{#                            <a href="{% url 'update_teacher' teacher.id %}" class="btn btn-warning">Update</a>#}
{#                        </div>#}
                        </div>
                    </div>
                </div>
            {% endif %}{% endif %}
        {% endfor %}
    </div>
{% endblock %}

templates/teacher/update_teacher.html
{% extends 'base.html' %}
{% block title %} Update student {% endblock %}
{% block content %}
    <div class="container"><br><br>
        <div class="row">
              <div class="col-md-6 offset-md-3">
                  <div class="card">
                      <div class="card-header">
                          <h3 class="text-center">Update teacher</h3>
                      </div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form.as_p }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </form>
                  </div>
              </div>
        </div>
    </div>

{% endblock %}