book/urls.py
from django.urls import path
from book import views

urlpatterns = [
    path('create-new-book/', views.BookCreateView.as_view(), name='create_new_book'),
    path('list-of-books/', views.BookListView.as_view(), name='all_books'),
    path('update-book/<int:pk>/', views.BookUpdateView.as_view(), name='update_book')
]

djangoProjectSDA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('intro.urls')),
    path('', include('student.urls')),
    path('', include('teacher.urls')),
    path('', include('home.urls')),
    path('', include('book.urls')),
    path('', include('userextend.urls')),
    path('', include('django.contrib.auth.urls')),
]

book/models.py
from django.db import models


class Book(models.Model):
    book_genres = (('Fantasy', 'Fantasy'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('SF', 'SF'),
                   ('Mystery', 'Mystery'), ('Other', 'Other'))

    book_title = models.CharField(max_length=30)
    author_name = models.CharField(max_length=30)
    cover = models.CharField(max_length=100)
    year = models.IntegerField()
    description = models.TextField()
    buy_link = models.CharField(max_length=100)
    genre = models.CharField(max_length=7, choices=book_genres)

    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.book_title} / {self.author_name}'

book/forms.py
from django import forms
from django.forms import TextInput, Textarea, Select

from book.models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['book_title', 'author_name', 'cover', 'year', 'description', 'buy_link', 'genre']
        widgets = {
            'book_title': TextInput(attrs={'placeholder': 'Please enter book title', 'class': 'form-control'}),
            'author_name': TextInput(attrs={'placeholder': 'Please enter author name', 'class': 'form-control'}),
            'cover': TextInput(attrs={'placeholder': 'Please enter cover image source', 'class': 'form-control'}),
            'year': TextInput(attrs={'placeholder': 'Please enter year of publication', 'class': 'form-control'}),
            'description': Textarea(attrs={'placeholder': 'Please enter description', 'class': 'form-control'}),
            'buy_link': TextInput(attrs={'placeholder': 'Please enter buy link', 'class': 'form-control'}),
            'genre': Select(attrs={'class': 'form-select'})
        }

book/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView

from book.forms import BookForm
from book.models import Book


class BookCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    template_name = 'book/create_book.html'  # calea catre fisierul html
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('create_new_book')


class BookListView(LoginRequiredMixin, ListView):
    template_name = 'book/list_of_books.html'
    model = Book
    context_object_name = 'all_books'


class BookUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = 'book/update_book.html'
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('all_books')

templates/book/create_book.html
{% extends 'base.html' %}
{% block title %} Create a new book {% endblock %}
{% block content %}
    <div class="container"><br><br>
        <div class="row">
              <div class="col-md-6 offset-md-3">
                  <div class="card">
                      <div class="card-header">
                          <h3 class="text-center">Create a new book</h3>
                      </div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form.as_p }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </form>
                  </div>
              </div>
        </div>
    </div>

{% endblock %}

templates/book/list_of_books.html
{% extends 'base.html' %}

{% block title %} List of books {% endblock %}

{% block content %}
    <div class="row">
        {% for book in all_books %}
{#            <div class="col-sm-4"><br>#}
{#                <div class="card" style="width: 18rem;">#}
{#                    <a data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">#}
{#                        <img src="{{ book.cover }}" class="card-img-top" alt="...">#}
{#                    </a>#}
{#                    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">#}
{#                        <div class="offcanvas-header">#}
{#                            <h5 class="offcanvas-title" id="offcanvasExampleLabel">{{ book.book_title }}</h5>#}
{#                            <h6 class="offcanvas-title" id="offcanvasExampleLabel">{{ book.author_name }}</h6>#}
{#                            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>#}
{#                        </div>#}
{#                        <div class="offcanvas-body">#}
{#                            <div>{{ book.description }}</div>#}
{#                        </div>#}
{#                        <div class="offcanvas-footer">#}
{#                            <div class="text-muted d-grid gap-2 col-6 mx-auto">#}
{#                            <a href="{% url 'update_book' book.id %}" class="btn btn-dark">Update</a>#}
{#                            </div><br><br>#}
{#                            <div class="container">#}
{#                                <div class="row">#}
{#                                    <div class="col">&nbsp&nbsp&nbsp{{ book.year }}</div>#}
{#                                    <div class="col text-end">{{ book.genre }}&nbsp&nbsp&nbsp</div>#}
{#                                </div><br>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
            <div class="col-sm-4"><br>
                <div class="card mb-3 scrollbar" style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="{{ book.cover }}" class="img-fluid rounded-start"  alt="...">
                            {% if perms.book.change_book %}
                                <div class="text-muted d-grid gap-2 col-6 mx-auto"><br>
                                <a href="{% url 'update_book' book.id %}" class="btn btn-dark">Update</a><br>
                                </div>
                            {% endif %}
                        </div>
                    <div class="col-md-8">
                    <div class="card-body" style="overflow-y:auto; max-height: 260px">
                        <h5 class="card-title">{{ book.book_title }}</h5>
                        <h6 class="card-title">{{ book.author_name }}</h6>
                        <div class="container">
                            <div class="row">
                                <div class="col">&nbsp&nbsp&nbsp{{ book.year }}</div>
                                <div class="col text-end">{{ book.genre }}&nbsp&nbsp&nbsp</div>
                            </div><br>
                        </div>
                        <p class="card-text">{{ book.description }}</p>
                    </div>
                    </div>
                    </div>
                </div>
            </div>
        {% endfor %}
{#        <button type="button" class="btn btn-lg btn-danger" data-bs-toggle="popover" title="Popover title" data-bs-content="And here's some amazing content. It's very engaging. Right?">Click to toggle popover</button>#}
{#        <a href="#" data-toggle="popover" title="Popover Header" data-content="Some content inside the popover">Toggle popover</a>#}
    </div>

{% endblock %}

templates/book/update_book.html
{% extends 'base.html' %}
{% block title %} Update book {% endblock %}
{% block content %}
    <div class="container"><br><br>
        <div class="row">
              <div class="col-md-6 offset-md-3">
                  <div class="card">
                      <div class="card-header">
                          <h3 class="text-center">Update book</h3>
                      </div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form.as_p }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </form>
                  </div>
              </div>
        </div>
    </div>

{% endblock %}