book/urls.py
from django.urls import path
from book import views

urlpatterns = [
    path('create-new-book/', views.BookCreateView.as_view(), name='create_new_book'),
    path('list-of-books/', views.BookListView.as_view(), name='all_books'),
    path('update-book/<int:pk>/', views.BookUpdateView.as_view(), name='update_book')
]

djangoProjectSDA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('intro.urls')),
    path('', include('student.urls')),
    path('', include('teacher.urls')),
    path('', include('home.urls')),
    path('', include('book.urls')),
    path('', include('userextend.urls')),
    path('', include('django.contrib.auth.urls')),
]

book/models.py
from django.db import models


class Book(models.Model):
    book_genres = (('Fantasy', 'Fantasy'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('SF', 'SF'),
                   ('Mystery', 'Mystery'), ('Other', 'Other'))

    book_title = models.CharField(max_length=30)
    author_name = models.CharField(max_length=30)
    cover = models.CharField(max_length=100)
    year = models.IntegerField()
    description = models.TextField()
    buy_link = models.CharField(max_length=100)
    genre = models.CharField(max_length=7, choices=book_genres)

    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.book_title} / {self.author_name}'

student/models.py
from django.db import models

from teacher.models import Teacher


class Student(models.Model):
    gender_options = (('male', 'Male'), ('female', 'Female'), ('other', 'Other'))

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(max_length=100)
    age = models.IntegerField()
    description = models.TextField()
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    is_olympic = models.BooleanField(default=False)
    gender = models.CharField(max_length=6, choices=gender_options)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, null=True)

    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

teacher/models.py
from django.db import models

# Create your models here.


class Teacher(models.Model):
    department_options = (('python', 'Python'), ('java', 'Java'), ('c#', 'C#'))

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    department = models.CharField(max_length=6, choices=department_options)
    course = models.CharField(max_length=100)
    description = models.TextField()
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %} </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/my_style.css' %}">
</head>
<body>
{%  include 'navbar.html' %}
{% block content %}

{% endblock %}
<footer class="page-footer pt-5">
    <div class="footer-copyright text-center py-3">© 2022 Copyright:
    <a href="/">SDAcademy.com</a>
  </div>
</footer>
{#<script>$(document).ready(function(){$('[data-toggle="popover"]').popover();});</script>#}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Django Project</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                 aria-expanded="false">
                Students
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% if perms.student.add_student %}
                    <li><a class="dropdown-item" href="{% url 'create_new_student' %}">Create a new student</a></li>
                      {% endif %}
                <li><a class="dropdown-item" href="{% url 'all_students' %}">List of students</a></li>
              </ul>
            </li>
              <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                 aria-expanded="false">
                Teachers
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% if perms.teacher.add_teacher %}
                      <li><a class="dropdown-item" href="{% url 'create_new_teacher' %}">Create a new teacher</a></li>
                  {% endif %}
                  <li><a class="dropdown-item" href="{% url 'all_teachers' %}">List of teachers</a></li>
              </ul>
            </li>
              <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                 aria-expanded="false">
                Books
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% if perms.book.add_book %}
                    <li><a class="dropdown-item" href="{% url 'create_new_book' %}">Create a new book</a></li>
                  {% endif %}
                  <li><a class="dropdown-item" href="{% url 'all_books' %}">List of books</a></li>
              </ul>
            </li>
             <li class="nav-item dropdown">
                 <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                    data-bs-toggle="dropdown" aria-expanded="false">
                     All Teachers
                 </a>
                 <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                     {% for teacher in teachers %}
                         <li><a class="dropdown-item" href="{% url 'all_students_per_teacher' teacher.id %}">
                             {{ teacher.first_name }} {{ teacher.last_name }}
                         </a></li>
                     {% endfor %}
                 </ul>
             </li>
        {% endif %}
      </ul>
      {% if user.is_authenticated %}
          <a href="{% url 'logout' %}" class="btn btn-outline-danger">Logout, {{ request.user.username }}</a>
      {% else %}
          <a href="{% url 'create_user' %}" class="btn btn-outline-secondary">Sign Up</a>
          <a href="{% url 'login' %}" class="btn btn-outline-success">Login</a>
      {% endif %}
    </div>
  </div>
</nav>